---
title: "How Constraining are Limits to Arbitrage?"
author: "Ljungqvist and Qian"
date: "January 22, 2019"
output:
  ioslides_presentation: default
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

+ Documents how small scale short-sellers overcome limits to arbitrage such as:
    + High shorting fees
    + few stocks available for borrowing
    + "Shallow pockets"
  
+ Proliferation of expensive (negative) information by arbitrageurs helps overcome their limits to arbitrage
+ Arbitrageurs use large sell-off of by those in long positions to profit from price discovery in wake of bad news

## Motivation and Contribution

+ How constraints affect mispricing and arbitrage (Getting around limits to arbitrage)
+ How short sellers produce and transmit information
+ Economic importance of even small arbitrageurs

## Main Research Question and Hypothesis

_How do, in wake of steep constraints, small scale short sellars effectuate arbitrage? Do big barriers to trading limit arbitrage?_ 

__Claim__: To counteract risk of trading against overvalued stocks where margin calls loom, small shorts which cannot exert downward pressure on prices, and time, the "arbs" share their signal with the market to reduce their exposure and let the unwinding long positions do the work. 

_"Arbs attempt to circumvent these constraints by making their information public, in an effort to persuade the longs to sell"_

## Main Research Question and Hypothesis

Need to test and examine:

(1) Impact of arbs information/signals in reports - how does market respond initially?
(2) Who is responsible for increased trading after a report is released?
(3) Credibility of reports - do the declines in price remain for long?



## Related Literature

Fits into greater Limits to Arbitrage literature, and more specifically evidence against it. 

+ Short selling constraints: DeLong, B., A.Shleifer, L.Summers, and R. Waldmann (1990)
    + Noise trader risk: potential for shorted stocks to increase in price and create ruinous margin calls
+ Benefits of advertising arbitrage: Kovbasyuk, S., and M. Pagano. 2014. Advertising arbitrage. Working Paper
    + In line with idea that promulgation of arbitrage opportunities might be good





## Data

+ Identify short sellers who:
    + Target allegedly overvalued companies 
    + Are not casual bloggers
    + Are not large hedge funds who restrict access to information
+ Total of 31 arbs
    + Earliest Firm founded in 1992, and most prolific ones include Citron and Muddy Waters
    + Little knowledge available due to private ownership
    
    
    
    
## Data 


  + This paper avoids bias by collecting every target firm of all 31 short sellers. 
  + 401 reports from 2006 to 2011 - only use 358 
  + 124 targeted listed companies come from these reports - remaining are follow-ups
    
After targeting, average abnormal return from 14 "first time" firms is -9.5% with 28.3% mean CAR profit for roughly 3 months.


## Data

+ Firms tend to be midsize growth stocks, in 70th percentile for turnover and 44th percentile for illiquidity. 
+ Shorting fees are high - in nearly 75th percentile
+ Not very lendable - only about 5%
+ Expensive put options
+ High idiosyncratic volatility (76th percentile)
+ Analysts' ratings were "buy" or "strong buy"
Not the kind of stock one would normally want to short!

    

Short sellars spend a lot of time and resouces investigating targets



## Primary Methodology and Tests

+ Assess impact of reports using Fama-French / momentum four-factor (and DGTW) cumulative abnormal returns in event time
+ After report, investors respond quickly in equity markets as prices fall by average of 7.51%
    + Suggest relevant and novel information
    + Prices continue to fall over next three months
    + SEC filing views increase 80% in one day
    + Trading activity increases 339% on release day
    
## Primary Methodology and Tests

Who is responsible for increased trading?

+ 0.45% of outstanding shares are newly shorted on day before report release (ANcerno and DataExplorers)
    + Cannot be responsible for large trade increase
    + After release, there is drastic increase in cost of shorting, and lendable stock supply falls
+ Options traders cannot arbitrage this information either
    + Implied put-option volatility remains significantly high after release, and put-call parity is high
        + So, its hard to get in and make much here, like it is hard to short sell
        
## Primary Methodology and Tests

Test Reaction of Long Investors

+ Disaggregate Trading Volume
    + Long volume = one-way volume - new shorts
    + Day following report shows massive increase of 524% of long volume
  
+ Used ANcerno data and separate aggregate selling and buying
    + Find ANcerno institutions seven times more active post report
    + All sells and no buys for these institutions
+ Also isolate target company in ANcerno data to see institution's holdings
    + ANcerno institutions sell average of 43% of target company on report release day
    + 65% of target's long investors are net sellers on report day
    
## Primary Methodology and Tests

Is information credible?

+ SEC filings and Factiva show 69% of target companies face class-action lawsuits, half are delisted, and over a third (36%) investigated by SEC or DoJ. 

+ 92% of targets change management, 47% have auditor turnover, and 23% restate earnings


## Primary Methodology and Tests

Also construct measure of credibility by measuring track record of arb's CARs 3 months before and separating those who had positive vs negative profits

+ Use simple difference in means test to show more credible group had significant returns $(p < 0.001)$, while less credible group was not significantly different than zero
+ Shorting fees also significantly greater for credible group, and not so otherwise
+ New evidence also significantly more valued than "opinion"



## Conclusion

+ Small Arbitrageurs can make a difference and help make markets great again (efficient)
+ Arbs use information to get long positions to unfold, thus winning on their short positions
+ Not just a knee-jerk reaction, but credible and lasting information 
+ If mispricing of assets is large, barriers can be overcome 
+ Short sellers can be a valuable part of market process, and not just manipulators

## Other thoughts and extensions

(1) An interesting study, though seemingly small sample - does it command attention, or is it just an interesting weekend read? Is it large enough to make the theoretical limit to arbitrage scholar shudder?

(2) How valuable is the greater literature on these topics? Life seems short for arbitrage opportunities


